
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phug-dev check --report

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z
